### ISSUE TITLE
requestTrackingAuthorization call returns immediately with denied value on iOS 17.4

### ISSUE THREAD

**Issue by szepeshazi** [deniza/app_tracking_transparency#50]
On iOS 17.4, the following call

```
// Show tracking authorization dialog and ask for permission
final status = await AppTrackingTransparency.requestTrackingAuthorization();
```

will display the prompt (if it was not displayed before) and will not wait for the prompt to be closed by user interaction, but rather returns immediately with a `TrackingStatus.denied` value. Once the prompt is closed by the user, on subsequent status checks the `await AppTrackingTransparency.trackingAuthorizationStatus` call will already return the proper value (as selected by the user).

Reproduced with version 2.0.4, on simulator (iPhone 15 / iOS 17.4) and real device (iPhone 13 mini / iOS 17.4)

**Comment by fatihemree** [comment]
Any progress? :(

**Comment by deniza** [comment]
Very strange. I just re-tested with my device, iPhone 11 and ios 17.4. It's working as expected. The thing is; i am showing a dialog (an explainer dialog) before triggering the native dialog. In this setup user triggers the function call by pressing a button from a flutter dialog widget. This may be preventing any time-dependent bugs bugs underneath. I am just taking a wild guess here.

Can you please test this out on your own testing environment? Just call AppTrackingTransparency.requestTrackingAuthorization(); from a button event handler, not from a widget init function.

**Comment by Bilonik** [comment]
@deniza getting the same bug even while using a button event handler

**Comment by Bilonik** [comment]
https://forums.developer.apple.com/forums/thread/748317

**Comment by martiina** [comment]
Having the same issue on iOS 17.3.1 and iOS 17.4.
requestTrackingAuthorization returns immediately TrackingStatus.denied.

iPhone 12 Pro

Also, the callback is triggered with button. Same issue as @Bilonik has.

**Comment by deniza** [comment]
Looks like building the app with Xcode 15.4 might be causing issues. To test this, I created a sample app using Xcode 15.3 and ran it successfully on a real iPhone with iOS 17.4.

As a temporary workaround, try building with Xcode 15.3. The good news is you can have multiple Xcode versions installed at once. Just download Xcode 15.3 from the official Apple Developer Downloads: https://developer.apple.com/download/all/

Once downloaded, use the xcode-select command-line tool to switch to the newly installed version. Rebuild your Flutter app and then test it on a real device or simulator running iOS 17.4.

**Comment by martiina** [comment]
Hi.
Thanks for the answer.

I ran with Xcode 15.3.

**Comment by jamlo** [comment]
Thanks @deniza for checking this.

Like @martiina, I am also using Xcode 15.3 when building the app, and the issue is happening when being reviewed by Apple. 

Since the issue occurrence is inconsistent, it feels like a race condition, where the plugin is not appropriately waiting for a certain signal from Apple APIs?

**Comment by xni06** [comment]
I reverted back to Xcode 15.2 from 15.3 using https://www.xcodes.app/ and it now works as expected again.

**Comment by nmaruy27** [comment]
I was also rejected several times due to the same issue, but after making corrections based on the code in the comment below, it was successfully approved and I was able to release it.

https://github.com/deniza/app_tracking_transparency/issues/47#issuecomment-1751719988

**Comment by deniza** [comment]
> Hi. Thanks for the answer.
> 
> I ran with Xcode 15.3 previously. Don't even have access to 15.4

Sorry, It's my bad. I tested it using Xcode 15.2 (not 15.3) and it's working as expected.

**Comment by jamlo** [comment]
FYI, even when I used Xcode 15.2 to build the app, it still had the same issue, and the app was rejected by Apple.

The following is the only solution that allowed the app to be accepted by Apple: https://github.com/deniza/app_tracking_transparency/issues/47#issuecomment-1746697074

**Comment by onursahindur** [comment]
Same here, still have the issue...

**Comment by adrian-fernandez** [comment]
Seems to be an issue from Apple fixed on iOS 17.5 beta but not yet on 17.4.*

https://forums.developer.apple.com/forums/thread/746432

**Comment by dionysos1** [comment]
untill this is fixed.

as the requestTrackingAuthorization returns isDenied but doesn't actually update the trackingStatus. I used a while loop to just check the status every second as you can't get around the request window as a user anyway. 

` /// Request system's tracking authorization dialog
  await AppTrackingTransparency.requestTrackingAuthorization();

  /// loop tracking status until it is no longer notDetermined
  while (await AppTrackingTransparency.trackingAuthorizationStatus == TrackingStatus.notDetermined) {
      await Future.delayed(const Duration(seconds: 1));
  }
  // code here that uses the actual status
`

**Comment by EliseiNicolae** [comment]
👋 hi there.
I had the same issue on real device.

What worked for me was running the followings:

1. Delete pod directory and podfile.lock
2. flutter clean
3. flutter pub get  
4. cd ios
5.  pod install --repo-update
6. flutter build ios

**Comment by serk87** [comment]
Make sure you have Settings > Privacy > Tracking enabled

**Comment by ervindobri** [comment]
Any updates? Issue still persists

**Comment by gcatak** [comment]
> 👋 hi there. I had the same issue on real device.
> 
> What worked for me was running the followings:
> 
> 1. Delete pod directory and podfile.lock
> 2. flutter clean
> 3. flutter pub get
> 4. cd ios
> 5. pod install --repo-update
> 6. flutter build ios
> 
> And then deploy to testflight using Archive. After that test it by downloading the version from TestFlight

Thanks, but which Xcode did you use? Does it work with Xcode 13? Any experience?

**Comment by jeweldeveloperr** [comment]
> 👋 hi there. I had the same issue on real device.
> 
> What worked for me was running the followings:
> 
> 1. Delete pod directory and podfile.lock
> 2. flutter clean
> 3. flutter pub get
> 4. cd ios
> 5. pod install --repo-update
> 6. flutter build ios
> 
> And then deploy to testflight using Archive. After that test it by downloading the version from TestFlight

Thanks, but which Xcode version did you use? Does it work with Xcode15.3?

**Comment by EliseiNicolae** [comment]
> > 👋 hi there. I had the same issue on real device.
> > What worked for me was running the followings:
> > 
> > 1. Delete pod directory and podfile.lock
> > 2. flutter clean
> > 3. flutter pub get
> > 4. cd ios
> > 5. pod install --repo-update
> > 6. flutter build ios
> > 
> > And then deploy to testflight using Archive. After that test it by downloading the version from TestFlight
> 
> Thanks, but which Xcode version did you use? Does it work with Xcode15.3?

I think it was Xcode 15.2

**Comment by jeweldeveloperr** [comment]
> > > 👋 hi there. I had the same issue on real device.
> > > What worked for me was running the followings:
> > > 
> > > 1. Delete pod directory and podfile.lock
> > > 2. flutter clean
> > > 3. flutter pub get
> > > 4. cd ios
> > > 5. pod install --repo-update
> > > 6. flutter build ios
> > > 
> > > And then deploy to testflight using Archive. After that test it by downloading the version from TestFlight
> > 
> > 
> > Thanks, but which Xcode version did you use? Does it work with Xcode15.3?
> 
> I think it was Xcode 15.2

Thanks for your answer. I don't want to remove pod directory and podfile.lock because I solved dozens of problems after I deleted it for different reason. 

I will try it in Xcode 15.3 without deleting pod files(or pod install) and inform you.

**Comment by deniza** [comment]
This issue should be fixed by now. Please update to version 2.0.6 of the plugin.

**Comment by marinat** [comment]
@deniza Hi, still having this issue on 2.0.6+1 (iOS 17.x, real device). requestTrackingAuthorization() returns immediately without waiting for user interaction.
(Update)
The problem with this behavior may be related to the fact that the ATT dialog was called before runApp(), and iOS requires an active UIWindow to display system dialogs; without it, it silently returns `notDetermined`
